databases:
  - name: senda-vida-db
    databaseName: senda_vida

services:
  - type: web
    name: senda-vida
    runtime: docker
    rootDir: BACKEND
    dockerfilePath: Dockerfile
    dockerContext: .
    envVars:
      - key: PORT
        value: 8084
      - key: DATABASE_URL
        fromDatabase:
          name: senda-vida-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
