-- Schema for senda_vida (PostgreSQL)
-- Generated from JPA entities in com.sendavida.models

BEGIN;

-- Drop order: children first (also uses CASCADE for safety)
DROP TABLE IF EXISTS clima CASCADE;
DROP TABLE IF EXISTS ubicacion_compartida CASCADE;
DROP TABLE IF EXISTS emergencia CASCADE;
DROP TABLE IF EXISTS foto CASCADE;
DROP TABLE IF EXISTS recomendacion CASCADE;
DROP TABLE IF EXISTS reto CASCADE;
DROP TABLE IF EXISTS hidratacion CASCADE;
DROP TABLE IF EXISTS alimentacion CASCADE;
DROP TABLE IF EXISTS contacto_emergencia CASCADE;
DROP TABLE IF EXISTS actividad CASCADE;
DROP TABLE IF EXISTS comunidad CASCADE;
DROP TABLE IF EXISTS ruta CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

CREATE TABLE usuario (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  edad INTEGER,
  peso DECIMAL(5,2),
  correo VARCHAR(100) NOT NULL UNIQUE,
  password VARCHAR(255) NOT NULL,
  foto VARCHAR(255),
  genero VARCHAR(255),
  preferencia VARCHAR(255),
  puntos_eco INTEGER,
  fcm_token VARCHAR(255),
  creado_en TIMESTAMP(6)
);

CREATE TABLE ruta (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo VARCHAR(50) NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  distancia_km DECIMAL(6,2),
  dificultad VARCHAR(255),
  nivel_seguridad VARCHAR(255),
  puntos_eco INTEGER,
  profundidad DECIMAL(6,2),
  longitud DECIMAL(6,2),
  ancho DECIMAL(6,2),
  altura DECIMAL(6,2),
  gps_inicio JSONB,
  gps_fin JSONB,
  mapa_offline BOOLEAN,
  datos_wikidata JSONB,
  area_protegida BOOLEAN,
  nombre_area VARCHAR(150),
  creado_en TIMESTAMP(6)
);

CREATE TABLE actividad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT,
  ruta_id BIGINT,
  tipo VARCHAR(255),
  distancia_recorrida DECIMAL(6,2),
  calorias DECIMAL(6,2),
  tiempo_segundos INTEGER,
  gps_recorrido JSONB,
  estado VARCHAR(255),
  iniciada_en TIMESTAMP(6),
  finalizada_en TIMESTAMP(6),
  CONSTRAINT fk_actividad_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
  CONSTRAINT fk_actividad_ruta FOREIGN KEY (ruta_id) REFERENCES ruta(id)
);

CREATE TABLE contacto_emergencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT,
  nombre VARCHAR(100) NOT NULL,
  telefono VARCHAR(20) NOT NULL,
  parentesco VARCHAR(255),
  activo BOOLEAN NOT NULL,
  CONSTRAINT fk_contacto_emergencia_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE reto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT,
  ruta_id BIGINT,
  tipo_reto VARCHAR(255),
  puntos INTEGER,
  estado VARCHAR(255),
  CONSTRAINT fk_reto_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
  CONSTRAINT fk_reto_ruta FOREIGN KEY (ruta_id) REFERENCES ruta(id)
);

CREATE TABLE recomendacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruta_id BIGINT,
  titulo VARCHAR(255),
  descripcion VARCHAR(255),
  importancia_ecologica VARCHAR(255),
  estado_conservacion VARCHAR(255),
  valor_natural VARCHAR(255),
  especies_gbif JSONB,
  actualizado_en TIMESTAMP(6),
  CONSTRAINT fk_recomendacion_ruta FOREIGN KEY (ruta_id) REFERENCES ruta(id)
);

CREATE TABLE hidratacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT,
  recordatorio VARCHAR(255),
  tiempo TIMESTAMP(6),
  completado BOOLEAN,
  CONSTRAINT fk_hidratacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE alimentacion (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT,
  sugerencia VARCHAR(255),
  tiempo TIMESTAMP(6),
  completado BOOLEAN,
  CONSTRAINT fk_alimentacion_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

CREATE TABLE foto (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT,
  ruta_id BIGINT,
  actividad_id BIGINT,
  gps JSONB,
  url_foto VARCHAR(255) NOT NULL,
  hora TIMESTAMP(6),
  CONSTRAINT fk_foto_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
  CONSTRAINT fk_foto_ruta FOREIGN KEY (ruta_id) REFERENCES ruta(id),
  CONSTRAINT fk_foto_actividad FOREIGN KEY (actividad_id) REFERENCES actividad(id)
);

CREATE TABLE emergencia (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT,
  ruta_id BIGINT,
  actividad_id BIGINT,
  ubicacion JSONB NOT NULL,
  tipo VARCHAR(255),
  estado VARCHAR(255),
  fecha TIMESTAMP(6),
  CONSTRAINT fk_emergencia_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
  CONSTRAINT fk_emergencia_ruta FOREIGN KEY (ruta_id) REFERENCES ruta(id),
  CONSTRAINT fk_emergencia_actividad FOREIGN KEY (actividad_id) REFERENCES actividad(id)
);

CREATE TABLE ubicacion_compartida (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  usuario_id BIGINT,
  ruta_id BIGINT,
  actividad_id BIGINT,
  gps JSONB,
  compartido_con JSONB,
  activa BOOLEAN,
  timestamp TIMESTAMP(6),
  CONSTRAINT fk_ubicacion_compartida_usuario FOREIGN KEY (usuario_id) REFERENCES usuario(id),
  CONSTRAINT fk_ubicacion_compartida_ruta FOREIGN KEY (ruta_id) REFERENCES ruta(id),
  CONSTRAINT fk_ubicacion_compartida_actividad FOREIGN KEY (actividad_id) REFERENCES actividad(id)
);

CREATE TABLE comunidad (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre_grupo VARCHAR(255) NOT NULL,
  descripcion VARCHAR(255),
  participantes INTEGER,
  codigo_invitacion VARCHAR(6) UNIQUE,
  mensajes JSONB
);

CREATE TABLE clima (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ruta_id BIGINT,
  temperatura DECIMAL(5,2),
  humedad DECIMAL(5,2),
  lluvia BOOLEAN,
  alerta VARCHAR(255),
  condicion VARCHAR(255),
  calidad_aire VARCHAR(255),
  fecha_registro TIMESTAMP(6),
  CONSTRAINT fk_clima_ruta FOREIGN KEY (ruta_id) REFERENCES ruta(id)
);

-- Helpful indexes for FKs
CREATE INDEX IF NOT EXISTS idx_actividad_usuario_id ON actividad(usuario_id);
CREATE INDEX IF NOT EXISTS idx_actividad_ruta_id ON actividad(ruta_id);
CREATE INDEX IF NOT EXISTS idx_contacto_emergencia_usuario_id ON contacto_emergencia(usuario_id);
CREATE INDEX IF NOT EXISTS idx_reto_usuario_id ON reto(usuario_id);
CREATE INDEX IF NOT EXISTS idx_reto_ruta_id ON reto(ruta_id);
CREATE INDEX IF NOT EXISTS idx_recomendacion_ruta_id ON recomendacion(ruta_id);
CREATE INDEX IF NOT EXISTS idx_hidratacion_usuario_id ON hidratacion(usuario_id);
CREATE INDEX IF NOT EXISTS idx_alimentacion_usuario_id ON alimentacion(usuario_id);
CREATE INDEX IF NOT EXISTS idx_foto_usuario_id ON foto(usuario_id);
CREATE INDEX IF NOT EXISTS idx_foto_ruta_id ON foto(ruta_id);
CREATE INDEX IF NOT EXISTS idx_foto_actividad_id ON foto(actividad_id);
CREATE INDEX IF NOT EXISTS idx_emergencia_usuario_id ON emergencia(usuario_id);
CREATE INDEX IF NOT EXISTS idx_emergencia_ruta_id ON emergencia(ruta_id);
CREATE INDEX IF NOT EXISTS idx_emergencia_actividad_id ON emergencia(actividad_id);
CREATE INDEX IF NOT EXISTS idx_ubicacion_compartida_usuario_id ON ubicacion_compartida(usuario_id);
CREATE INDEX IF NOT EXISTS idx_ubicacion_compartida_ruta_id ON ubicacion_compartida(ruta_id);
CREATE INDEX IF NOT EXISTS idx_ubicacion_compartida_actividad_id ON ubicacion_compartida(actividad_id);
CREATE INDEX IF NOT EXISTS idx_clima_ruta_id ON clima(ruta_id);

COMMIT;

